// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeCategorizationSystem.Infrastructure;

#nullable disable

namespace TradeCategorizationSystem.Infrastructure.Migrations
{
    [DbContext(typeof(TradeCategoryDbContext))]
    [Migration("20250209200801_CaptureCurrentModelState")]
    partial class CaptureCurrentModelState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("TradeCategorizationSystem.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientSector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("FinalValue")
                        .HasColumnType("REAL");

                    b.Property<double>("InitialValue")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
