jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          ref: 'master'

      - name: Definir nome da branch com a data yyyymmaa
        id: branch_name
        run: echo "branch_name=preprod_$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Criar e push da branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b ${{ steps.branch_name.outputs.branch_name }}
          git push origin ${{ steps.branch_name.outputs.branch_name }}
