name: Criar Branch Preprod

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'Data (YYYYMMDD) para o nome da branch (Ex: 20250815)'
        required: true
        # Uma forma mais robusta de garantir que a data está presente
        default: '20250815'

jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Adiciona permissão de escrita para o token
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          repository: 'airtonomoreira/airtonomoreira-TradeCategorizationSystem'
          # A branch 'main' sempre deve existir, use-a como base
          ref: 'main'
          fetch-depth: 0

      - name: Definir nome da branch com a data de hoje
        id: branch_name
        # Adicione a data no nome da branch a partir do input
        run: echo "branch_name=preprod_${{ github.event.inputs.data }}" >> $GITHUB_ENV

      - name: Criar a nova branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b ${{ env.branch_name }}
          git push origin ${{ env.branch_name }}
