# Este fluxo de trabalho faz o merge de uma branch de release para a branch de preprod
name: Merge Release to Preprod

on:
  push:
    # Aciona o workflow sempre que houver um push para qualquer branch que comece com 'release/'
    branches:
      - 'release/**'

jobs:
  merge-to-preprod:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permite que o workflow escreva no reposit칩rio (para o merge e push)
    
    steps:
      - name: Checkout da branch de destino (preprod)
        uses: actions/checkout@v4
        with:
          # Alterado para o nome real da sua branch de preprod
          ref: 'preprod_20250815' 
          fetch-depth: 0

      - name: Configurar usu치rio e email do Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Fazer o merge e o push para a branch de preprod
        run: |
          # Fazer o merge da branch 'release' para a 'preprod'.
          # O comando ir치 falhar automaticamente se houver um conflito.
          git merge --no-ff ${{ github.ref }}

          # Se o merge foi bem-sucedido, fazer o push para o reposit칩rio.
          git push origin HEAD
